use customer_analysis;
#Q1. what is the total revenue revenue generated by male vs. female customers?
SELECT gender, SUM(`purchase_amount_(usd)`) AS revenue
FROM mytable
GROUP BY gender;


#02. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, `purchase_amount_(usd)`
FROM mytable
WHERE discount_applied = 'Yes'
  AND `purchase_amount_(usd)` >= (
    SELECT AVG(`purchase_amount_(usd)`) FROM mytable
  );


#03. Which are the top 5  products with the highest average review rating?
select  item_purchased, avg(review_rating) as avg_rating
from mytable 
group by item_purchased 
order by avg_rating desc limit 5;



#Qa. Compare the average Purchase Amount between Standard and Express Shipping.
select shipping_type,avg(`purchase_amount_(usd)`) as avg_purchase
from mytable
group by shipping_type;

#QS. Do subscribed customers spend more? Compare average spend and total revenue betiveen subscribers and non-subscribers
select subscription_status,avg(`purchase_amount_(usd)`) as avg_spend ,sum(`purchase_amount_(usd)`) as total_revenue
from mytable 
group by subscription_status;

#06. which products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * sum( CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END )/COUNT(*),2)as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

#07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT CASE
         WHEN previous_purchases = 1 THEN 'New'
         WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
         ELSE 'Loyal'
       END AS customer_segment,
       COUNT(*) AS count
FROM mytable
GROUP BY customer_segment;

#08. what are the top 3 most purchased products within each category
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS arank
    FROM mytable
    GROUP BY category, item_purchased
) AS ranked
WHERE arank <= 3;

WITH item_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;


#Q9. Are customers who are repeat buyers (more than 5 previous
 select subscription_status,
 count(customer_id) as repeat_buyers
 from mytable
  where previous_purchases >5
 group by subscription_status
 ;
 #what was tthe revenue contribution based on the age group
 select age_group,
 sum(`purchase_amount_(usd)`) as total_revenue
 from mytable
 group by age_group
 order by total_revenue desc;
 
